### ISSUE TITLE
Potential quality of life changes request

### ISSUE THREAD

**Issue by Hashibane** [0stam/psio-game#17]
### This issue contains potential changes:
1. New function `refreshTile` in **EditorMapDisplay**
+Avoiding repainting whole map, instead we repaint just one tile section.
2. Make **EditorMapDisplay** or (more reasonable) EditorDisplay singleton. 
+Easy access to functions like `refreshMap` and  `refreshTile` (Difficulity in **Editor** and **ToolPalette**)
+It would make static calls to above mentioned functions possible (currently mapTiles is not static and so it's not possible to make `refreshMap` or `refreshTile` static)
+If `refreshMap`, `refreshTile` were to be static then so would be `mapTiles` - so almost all instance variables are static.
-Maybe I am not taking more instances of Editor into consideration. Seems counter-intuitive to have more than one anyway.
3. Code imrovements
One "global" hashtable should be used to avoid purposeless references - eg: duplicate reference to "global" graphics hashtable in **TilePalette**:
```
public class TilePalette extends JPanel {
	private Hashtable<enums.Graphics, BufferedImage> fileNames;
...
public TilePalette () {
		fileNames = GraphicsHashtable.getInstance().getImages();
...
       }
}
```

Nie wiem czy taka forma wam odpowiada - mi na pewno, bo mogę łatwo i czysto wyrazić myśli. Chyba jeszcze było parę rzeczy, które zostały zrobione trochę, żeby działało (jednak się śpieszyliśmy), nie pamiętam już wszystkich. Głównie jednak chodzi o edytor jako singleton i refreshTile.

**Comment by 0stam** [comment]
W kilku miejscach się nie zgadzamy, ale mam nadzieję, że z dyskusji wyjdzie coś ciekawego :D
Jak coś dalej nie będę pisał rzeczy typu "w mojej opinii" ani nic takiego, więc momentami może brzmieć ostro, ale z wszystkim oczywiście możesz się nie zgodzić.

Po pierwsze, problem z logiką edytora odświeżającą mapę nie istnieje. Po prostu w drawEditor() nie możemy wywoływać editorDisplay.repaint() ze Swinga, tylko EditorDisplay powinien mieć metodę update, która wywołuję metodę update w mapie. To prawdopodobnie jest sugerowane rozwiązanie niezależnie od wszystkich innych zmian, które możemy tu wprowadzić.

Na pewno nie chcemy, żeby logika bezpośrednio wywoływała metodę w konkretnej klasie z wyświetlaniem, bo separację i cały zamysł z różnymi metodami interakcji z użytkownikiem trafia szlag. Logika powinna wywoływać tylko metody IOManager'a.

> New function refreshTile in EditorMapDisplay

Co do zasady nie mam nic przeciwko, ale wtedy logika musiałaby decydować, którego Tile'a odświeżyć. Zakładając, że logika widzi tylko IOManager'a, IOManager musiałby mieć metodę refreshEditorTile(x, y) albo coś w tym stylu.

> Make EditorMapDisplay or (more reasonable) EditorDisplay singleton.

Intuicja podpowiada mi, że nie można zrobić Singletona z czegoś, co normalnie uczestniczy w strukturze klas i jest agregowane przez inne klasy. Szczerze mówiąc, tutaj nie umiem podać uzasadnienia, dlaczego to miałby być zły pomysł z perspektywy implementacji.
Na pewno nie podoba mi się tutaj koncepcyjna organizacja kodu, że jeśli coś jest statyczne, to z założenia nie powinno zależeć od stanu innych rzeczy, a tutaj np. czasem ten obiekt edytora będziemy chcieli usunąć, jak nie jest wykorzystywany itp.

Mam za to dwa alternatywne rozwiązania:
1. Wszystkie klasy agregowane przez edytor mają referencję do edytora. Koncepcyjnie ma dużo więcej sensu, a jedyny minus jest taki, że zużywa nieco więcej pamięci, co powinno być pomijalne.
2. Przenosimy całe zapamiętywanie stanu (warstwy, wybrany tile na palecie itd.) do LOGIKI edytora i dodajemy metodę getEditor() do GameManagera. Logika na pewno będzie tylko jedna, bo jest w GameManagerze. To koncepcyjnie też mi się podoba, bo nie trzymamy wtedy statycznych rzeczy w grafice.

Wersja pierwsza jest bardzo prosta do wprowadzenia, za to wersja druga podoba mi się bardziej, tylko zmiana wtedy jest już inwazyjna na tym etapie.

> One "global" hashtable should be used to avoid purposeless references - eg: duplicate reference to "global" graphics hashtable in TilePalette:

A ten globalny HashTable już przypadkiem nie istnieje, tylko ktoś zapomniał go tam użyć?
